include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Reglas de Limpieza ---
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    
    # --- Mejores Prácticas ---
    prefer_const_constructors: true
    prefer_final_locals: true
    # DESACTIVAMOS ESTA para que no te moleste con cambiar las rutas de los archivos
    prefer_relative_imports: false 
    always_declare_return_types: true
    avoid_print: true
    use_build_context_synchronously: true
    
    # --- Estilo ---
    prefer_single_quotes: true